spring:
  security:
   oauth2:
     client:
       registration:
         github:
           clientId: xxx
           clientSecret: xxx
         google:
          clientId: xx
          clientSecret: xx
         facebook:
          clientId: xx
          clientSecret: xx
          accessTokenUri: https://graph.facebook.com/oauth/access_token
          userAuthorizationUri: https://www.facebook.com/dialog/oauth
          tokenName: oauth_token
          authenticationScheme: query
          clientAuthenticationScheme: form
     resource:
       userInfoUri: https://graph.facebook.com/me
            